###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    database:
      image: mysql:latest
      container_name: database
      working_dir: /application
      volumes:
        - ./dbdata/mysql:/var/lib/mysql
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      environment:
        - MYSQL_ROOT_PASSWORD=hardcore
      ports:
        - "3307:3306"

    webserver:
      image: nginx:alpine
      container_name: webserver
      working_dir: /application
      volumes:
          - ../website:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"
      depends_on:
        - database

    website:
      build: phpdocker/config
      container_name: website
      working_dir: /application
      volumes:
        - ../website:/application
        - ./phpdocker/config/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini